package eg.iti.shareit.model.dto;

// Generated Nov 9, 2015 9:29:03 PM by Hibernate Tools 4.0.0
import eg.iti.shareit.common.dto.GenericDto;
import eg.iti.shareit.model.entity.ItemEntity;
import eg.iti.shareit.model.entity.NotificationEntity;
import java.math.BigDecimal;
import java.util.List;

/**
 * UserDto generated by hbm2java
 */
public class UserDto implements java.io.Serializable, GenericDto {

    private BigDecimal id;
    private String email;
    private String username;
    private String password;
    private String imageUrl;
    private int points;
    private GenderDto gender;
    private AddressDto address;
    private List<ItemDto> items;
    private List<NotificationDto> notificationFromUserList;
    private List<NotificationDto> notificationToUserList;

    public UserDto() {
    }

    public UserDto(BigDecimal id, String username) {
        this.id = id;
        this.username = username;
    }

    public UserDto(BigDecimal id, String email, String username, String password, String imageUrl, int points, GenderDto gender) {
        this.id = id;
        this.email = email;
        this.username = username;
        this.password = password;
        this.imageUrl = imageUrl;
        this.points = points;
        this.gender = gender;
    }

    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public int getPoints() {
        return points;
    }

    public void setPoints(int points) {
        this.points = points;
    }

    public GenderDto getGender() {
        return gender;
    }

    public void setGender(GenderDto gender) {
        this.gender = gender;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public AddressDto getAddress() {
        return address;
    }

    public void setAddress(AddressDto address) {
        this.address = address;
    }

    public List<NotificationDto> getNotificationFromUserList() {
        return notificationFromUserList;
    }

    public void setNotificationFromUserList(List<NotificationDto> notificationFromUserList) {
        this.notificationFromUserList = notificationFromUserList;
    }

    public List<NotificationDto> getNotificationToUserList() {
        return notificationToUserList;
    }

    public void setNotificationToUserList(List<NotificationDto> notificationToUserList) {
        this.notificationToUserList = notificationToUserList;
    }

    public List<ItemDto> getItems() {
        return items;
    }

    public void setItems(List<ItemDto> items) {
        this.items = items;
    }

    @Override
    public String toString() {
        return "UserDto{" + "id=" + id + ", email=" + email + ", username=" + username + ", password=" + password + ", imageUrl=" + imageUrl + ", points=" + points + ", gender=" + gender + ", address=" + address + ", items=" + items + ", notificationFromUserList=" + notificationFromUserList + ", notificationToUserList=" + notificationToUserList + '}';
    }

}
